# A workflow to send Notifications to telegram after a Pull Request Opened
name: Pull request Notifier
on:
    push: 
        branches:
            - '*'
    pull_request:
      types: [opened, reopened,  closed, assigned, review_requested]
    
    fork: 

jobs:
  notify_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract and format reviewers
        id: extract_reviewers
        run: |
          mentioned_users=$(jq -r '.pull_request.requested_reviewers | map("@" + .login) | join(" ")' $GITHUB_EVENT_PATH)
          echo "::set-output name=mentioned_users::$mentioned_users"

      - name: Send telegram message on pull request
        if: github.event_name == 'pull_request'
        uses: appleboy/telegram-action@master
        with:
          to: -4180709325
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🙀 ${{ github.actor }} created PR:
            Pull_request title: ${{ github.event.pull_request.title }}
            Requested Reviewers: ${{ steps.extract_reviewers.outputs.mentioned_users }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/files

  notify_push:
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push
        if: github.event_name == 'push'
        uses: appleboy/telegram-action@master
        with:
          to: -4180709325
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            😅 ${{ github.actor }} pushed to branch ${{ github.ref }} in repository ${{ github.repository }}


  notify_fork:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on fork
        if: github.event_name == 'fork'
        uses: appleboy/telegram-action@master
        with:
          to: -4180709325
          token: 7116884411:AAFl-Wy_azTnQQrSgsjkLw1rd74a7F13-Vc
          message: |
            🍴 ${{ github.actor }} forked repository ${{ github.repository }}.
            ⚠️ ${{ github.actor }} this is the intellecutal property of the group. Be careful on any actions you take.
